from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol

from .transitions import TransitionBatch


class AlgorithmPlugin(Protocol):
    """Learning and policy boundary."""

    def configure(
        self, observation_spec: dict[str, Any], action_spec: dict[str, Any], config: dict[str, Any]
    ) -> None: ...
    def train_step(self, batch: TransitionBatch) -> dict[str, float]: ...
    def sample_actions(self, observations: Any, deterministic: bool = False) -> Any: ...
    def save(self, path: Path) -> None: ...
    def load(self, path: Path) -> None: ...
    def export(self, format_name: str) -> bytes: ...
