from __future__ import annotations

from typing import Any, Protocol


class ComputeBackend(Protocol):
    """Job execution boundary"""

    def launch(self, job: Any) -> Any: ...
    def status(self, handle: Any) -> str: ...
    def cancel(self, handle: Any) -> None: ...
    def artifacts(self, handle: Any) -> list[str]: ...
