from __future__ import annotations

from typing import Any, Protocol


class SimBackend(Protocol):
    """Simulator boundary"""

    def load(self, robot_spec: dict[str, Any], sim_config: dict[str, Any]) -> None: ...
    def reset(self, batch_size: int) -> Any: ...
    def step(self, actions: Any) -> Any: ...
    def observation_spec(self) -> dict[str, Any]: ...
    def action_spec(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
